# training settings
batch_size: 2
epochs: 30
learning_rate: 0.0001
dataset_dir: "/home/matija/Luxonis/people-detseg/data/StrawDI_Db1"
runs_dir: "runs/" # relative to project dir
warmup: 'linear'
warmup_iters: 100

# demo
demo_run: "exp4"

# model settings
anchors: [[18,21,  30,34,  43,53,],[52,75,  69,87,  71,118],  [90,135,  102,174,  131,215]]
num_classes: 1
strides: [40, 20, 10]

# augmentations
img_shape: [480, 640]
blur_p: 0.4
blur_ks: 10
flip_p: 0.5
rotate_p: 15
min_scale: 0.9