# training settings

dataset: "cocopeople"

batch_size: 2
epochs: 30
optimizer: "sgd"
learning_rate: 0.01
dataset_dir: "/home/matija/fiftyone/coco-2017"
runs_dir: "runs/" # relative to project dir
warmup: 'linear'
warmup_iters: 200
momentum: 0.937
weight_decay: 0.00005
pretrained:  #"runs/exp52/best.pt"
num_workers: 0

decoder: True
backbone: True
head_seg: False
head_det: True

w_box: 0.05
w_cls: 0.3
w_obj: 1
w_iou: 0.1
w_seg: 0.1

# val
val_plot_num: 4
thr_iou: 0.6
thr_conf: 0.3

# model settings
reduction: 4    # by how much reduce the number of channels
num_classes: 1

# 3 head version
anchors: [[9,6, 7,3, 5,27,  7,56,  15,51],  [25,9, 33,23, 11,95,  18,107,  20,166],  [61,25, 78,63, 32,142,  37,244,  66,336]]
strides: [8,16,32]
# 2 head version
#anchors: [[5,36,  9,61,  13,109],  [21,94,  23,167,  43,241]]
#strides: [16,32]

# augmentations
img_shape: [480, 864]
blur_p: 0.4
blur_ks: 10
flip_p: 0.5
rotate_p: 15
min_scale: 0.9

# demo
demo_run: "exp33"