# training settings

dataset: "cocopeople"

batch_size: 16
epochs: 300
optimizer: "sgd" #"adam"
learning_rate: 0.005 #0.0005
dataset_dir: "/home/paperspace/fiftyone/coco-2017"
runs_dir: "runs/" # relative to project dir
warmup: 'linear'
warmup_iters: 5000
momentum: 0.937
weight_decay: 0.0005
pretrained:  "runs/exp37/best.pt"
num_workers: 6

decoder: True
backbone: True
head_seg: True
head_det: True

w_box: 0.05
w_cls: 0.3
w_obj: 1
w_iou: 0.1
w_seg: 0.1

# val
val_plot_num: 4
thr_iou: 0.2
thr_conf: 0.4

# model settings
reduction: 2    # by how much reduce the number of channels
num_classes: 1

# 3 head version - pretrained directly
anchors: [[10,13,16,30,33,23,36,57,64,22],[30,61,62,45,59,119,394,487,232,80],[116,90,156,198,373, 326,394,487,484,182]]
strides: [8,16,32]
# 3 head version - coco
# anchors: [[9,19,  19,35,  26,66, 72,22],  [53,90,  66,185,  124,143,  286,95],  [126,302,  245,396,  440,417,  603,226]]    
# strides: [8,16,32]
# 2 head version
#anchors: [[5,36,  9,61,  13,109],  [21,94,  23,167,  43,241]]
#strides: [16,32]

# augmentations
img_shape: [640, 640]
blur_p: 0.4
blur_ks: 10
flip_p: 0.5
rotate_p: 15
min_scale: 0.9

# demo
demo_run: "exp37"