# training settings

dataset: "strawdi"

batch_size: 2
epochs: 1000
learning_rate: 0.0001
dataset_dir: "./data/StrawDI_Db1"
runs_dir: "runs/" # relative to project dir
warmup: 'linear'
warmup_iters: 100

decoder: True
backbone: True
head_seg: False
head_det: True

w_box: 0.05
w_cls: 0.3
w_obj: 1
w_iou: 0.1
w_seg: 0.1

# val
val_plot_num: 4
thr_iou: 0.3
thr_conf: 0.3

# demo
demo_run: "exp21"

# model settings
reduction: 1    # by how much reduce the number of channels
num_classes: 1

# 2 head version
anchors: [[8,15,  14,23,  20,35],  [26,51,  31,73,  42,60],  [40,95,  49,118,  61,151]]
strides: [8,16,32]
# 3 head version
#anchors: [[13,22,  21,35,  31,60], [41,94,  55,129,  73,174]]
#strides: [8,16]

# augmentations
img_shape: [480, 640]
blur_p: 0.4
blur_ks: 10
flip_p: 0.5
rotate_p: 15
min_scale: 0.9